// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.Infrastructure;

#nullable disable

namespace ToDo.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250823204435_SeededDatabase")]
    partial class SeededDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDo.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "JohnDoeEmail123@gmail.com",
                            Name = "John",
                            Password = "John123",
                            Surname = "Doe"
                        },
                        new
                        {
                            Id = 2,
                            Email = "AliceSmith456@gmail.com",
                            Name = "Alice",
                            Password = "Alice456",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "RobertJ789@gmail.com",
                            Name = "Robert",
                            Password = "Robert789",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 4,
                            Email = "EmilyBrown101@gmail.com",
                            Name = "Emily",
                            Password = "Emily101",
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 5,
                            Email = "MichaelDavis202@gmail.com",
                            Name = "Michael",
                            Password = "Michael202",
                            Surname = "Davis"
                        },
                        new
                        {
                            Id = 6,
                            Email = "SophiaWilson303@gmail.com",
                            Name = "Sophia",
                            Password = "Sophia303",
                            Surname = "Wilson"
                        },
                        new
                        {
                            Id = 7,
                            Email = "DavidMiller404@gmail.com",
                            Name = "David",
                            Password = "David404",
                            Surname = "Miller"
                        });
                });

            modelBuilder.Entity("ToDo.Domain.Entities.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 279, DateTimeKind.Local).AddTicks(4507),
                            Description = "Buy strawberry ice cream",
                            Priority = 1,
                            Title = "Buy ice cream",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5175),
                            Description = "Complete the quarterly report",
                            Priority = 3,
                            Title = "Finish report",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5191),
                            Description = "Discuss project details",
                            Priority = 2,
                            Title = "Call Mike",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Deadline = new DateTime(2025, 8, 27, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5194),
                            Description = "Buy vegetables and fruits",
                            Priority = 2,
                            Title = "Grocery shopping",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Deadline = new DateTime(2025, 8, 28, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5196),
                            Description = "Organize office desk",
                            Priority = 1,
                            Title = "Clean desk",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Deadline = new DateTime(2025, 8, 28, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5201),
                            Description = "Organize Alice's birthday party",
                            Priority = 2,
                            Title = "Plan birthday party",
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5203),
                            Description = "Milk, eggs, and bread",
                            Priority = 1,
                            Title = "Buy groceries",
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5205),
                            Description = "Attend yoga class",
                            Priority = 2,
                            Title = "Gym session",
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5206),
                            Description = "Schedule dental checkup",
                            Priority = 3,
                            Title = "Call dentist",
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Deadline = new DateTime(2025, 8, 27, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5209),
                            Description = "Read 20 pages of a novel",
                            Priority = 1,
                            Title = "Read book",
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5211),
                            Description = "Repair the front tire",
                            Priority = 3,
                            Title = "Fix bike",
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Deadline = new DateTime(2025, 8, 30, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5212),
                            Description = "Finish reading 'C# in Depth'",
                            Priority = 1,
                            Title = "Read book",
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5214),
                            Description = "Weekly project meeting",
                            Priority = 2,
                            Title = "Team meeting",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            Deadline = new DateTime(2025, 8, 27, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5226),
                            Description = "Add recent projects",
                            Priority = 3,
                            Title = "Update resume",
                            UserId = 3
                        },
                        new
                        {
                            Id = 15,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5228),
                            Description = "Wash clothes",
                            Priority = 1,
                            Title = "Laundry",
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5230),
                            Description = "Roses for mom",
                            Priority = 1,
                            Title = "Buy flowers",
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5231),
                            Description = "History assignment",
                            Priority = 3,
                            Title = "Submit assignment",
                            UserId = 4
                        },
                        new
                        {
                            Id = 18,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5234),
                            Description = "Deep clean the kitchen",
                            Priority = 2,
                            Title = "Clean kitchen",
                            UserId = 4
                        },
                        new
                        {
                            Id = 19,
                            Deadline = new DateTime(2025, 8, 28, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5236),
                            Description = "Photography workshop",
                            Priority = 2,
                            Title = "Attend workshop",
                            UserId = 4
                        },
                        new
                        {
                            Id = 20,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5238),
                            Description = "Morning meditation session",
                            Priority = 1,
                            Title = "Meditation",
                            UserId = 4
                        },
                        new
                        {
                            Id = 21,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5239),
                            Description = "Electricity and internet",
                            Priority = 3,
                            Title = "Pay bills",
                            UserId = 5
                        },
                        new
                        {
                            Id = 22,
                            Deadline = new DateTime(2025, 8, 27, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5241),
                            Description = "Gift for friend's wedding",
                            Priority = 2,
                            Title = "Buy gift",
                            UserId = 5
                        },
                        new
                        {
                            Id = 23,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5271),
                            Description = "Learn about Blazor Server",
                            Priority = 1,
                            Title = "Watch tutorial",
                            UserId = 5
                        },
                        new
                        {
                            Id = 24,
                            Deadline = new DateTime(2025, 9, 2, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5273),
                            Description = "Decide destination and dates",
                            Priority = 2,
                            Title = "Plan vacation",
                            UserId = 5
                        },
                        new
                        {
                            Id = 25,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5275),
                            Description = "Clean interior and exterior",
                            Priority = 1,
                            Title = "Car wash",
                            UserId = 5
                        },
                        new
                        {
                            Id = 26,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5276),
                            Description = "Annual checkup",
                            Priority = 3,
                            Title = "Doctor appointment",
                            UserId = 6
                        },
                        new
                        {
                            Id = 27,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5278),
                            Description = "Chocolate cake for party",
                            Priority = 2,
                            Title = "Bake cake",
                            UserId = 6
                        },
                        new
                        {
                            Id = 28,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5280),
                            Description = "Evening walk in park",
                            Priority = 1,
                            Title = "Walk the dog",
                            UserId = 6
                        },
                        new
                        {
                            Id = 29,
                            Deadline = new DateTime(2025, 8, 28, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5282),
                            Description = "Organize tools and boxes",
                            Priority = 2,
                            Title = "Clean garage",
                            UserId = 6
                        },
                        new
                        {
                            Id = 30,
                            Deadline = new DateTime(2025, 8, 27, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5283),
                            Description = "Cybersecurity topic",
                            Priority = 3,
                            Title = "Read research paper",
                            UserId = 6
                        },
                        new
                        {
                            Id = 31,
                            Deadline = new DateTime(2025, 8, 28, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5285),
                            Description = "Oil change and tire rotation",
                            Priority = 3,
                            Title = "Car service",
                            UserId = 7
                        },
                        new
                        {
                            Id = 32,
                            Deadline = new DateTime(2025, 8, 24, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5287),
                            Description = "Math exercises",
                            Priority = 2,
                            Title = "Finish homework",
                            UserId = 7
                        },
                        new
                        {
                            Id = 33,
                            Deadline = new DateTime(2025, 8, 25, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5289),
                            Description = "Weekly check-in call",
                            Priority = 1,
                            Title = "Call parents",
                            UserId = 7
                        },
                        new
                        {
                            Id = 34,
                            Deadline = new DateTime(2025, 8, 26, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5291),
                            Description = "Prepare weekly meal plan",
                            Priority = 2,
                            Title = "Grocery shopping",
                            UserId = 7
                        },
                        new
                        {
                            Id = 35,
                            Deadline = new DateTime(2025, 8, 27, 23, 44, 35, 280, DateTimeKind.Local).AddTicks(5293),
                            Description = "Sort and arrange bookshelf",
                            Priority = 1,
                            Title = "Organize books",
                            UserId = 7
                        });
                });

            modelBuilder.Entity("ToDo.Domain.Entities.UserTask", b =>
                {
                    b.HasOne("ToDo.Domain.Entities.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDo.Domain.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
